services:
  mongodb:
    image: mongo:7
    container_name: geo-mongodb
    ports:
      - "27017:27017"
    volumes:
      - ./mongo_data:/data/db
    restart: unless-stopped

  qdrant:
    image: qdrant/qdrant:latest
    container_name: geo-qdrant
    ports:
      - "6333:6333"
      - "6334:6334"
    volumes:
      - ./qdrant_data:/qdrant/storage
    restart: unless-stopped
